### ISSUE TITLE
关于论文的一点咨询...

### ISSUE THREAD

**Issue by dalaeyelids** [Lancelot-wy/Anhui-Agricultural-University-LaTeX-Template-of-Undergraduate-Thesis#1]
作者您好！拜读了您与2023年发表在plants上的论文MFBP-UNet: A Network for Pear Leaf Disease Segmentation in Natural Agricultural Environments。这篇论文中精美的图表给我留下了深刻的印象。能否向您请教使用何种工具绘制的折线图，感谢！！

**Comment by Lancelot-wy** [comment]
表格为Latex调试生成，基本美观即可，折线图由Origin绘制，调色用了色彩网站上提供的色彩配置，并不专业也算不上精美，希望能对你有帮助！
